version: '3'
services:

  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  pgbouncer:
    image: deed-pgbouncer:ssl
    build: ./
    environment:
       - PGBOUNCER_PORT=5432
       - PGBOUNCER_AUTH_USER=postgres
       - POSTGRESQL_PASSWORD=password
       - POSTGRESQL_USERNAME=postgres
       - PGBOUNCER_INITSCRIPTS_DIR=/opt/bitnami/pgbouncer/custom_scripts
       - PGBOUNCER_FORCE_INITSCRIPTS=true
       - PGBOUNCER_CLIENT_TLS_SSLMODE=require
       - PGBOUNCER_CLIENT_TLS_CERT_FILE=/opt/bitnami/pgbouncer/certs/pgbouncer.crt
       - PGBOUNCER_CLIENT_TLS_KEY_FILE=/opt/bitnami/pgbouncer/certs/pgbouncer.key
    ports:
      - "5432:5432"
    depends_on:
      - postgresql
