version: '3'
services:

  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  pgbouncer:
    image: deed-pgbouncer:ssl
    build: ./
    env_file: .env.local
    ports:
      - "5432:5432"
    depends_on:
      - postgresql
